cloakd_communication_tool:	cloakd_communication_tool.o
	gcc -o cloakd_communication_tool cloakd_communication_tool.o

cloakd_communication_tool.o:	cloakd_communication_tool.c
	gcc -c cloakd_communication_tool.c

clean:
	rm *.o cloakd_communication_tool	
